# .github/workflows/ci.yml

name: BeesCover CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build-and-test:
    name: Smart Contract Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22.17.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.0

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: 'node_modules'
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run tests
        run: npx hardhat test

      - name: Run coverage
        if: always()
        run: npx hardhat coverage

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  mythril:
    name: Mythril Security Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Mythril
        run: |
          pip install --upgrade pip
          pip install mythril

      - name: 🔎 Analyze contracts with Mythril (excluding mocks/interfaces)
        run: |
          mkdir -p flattened
          find contracts -type f -name "*.sol" ! -path "*/mock/*" ! -path "*/interfaces/*" | while read file; do
            echo "Flattening $file..."
            filename=$(basename "$file")
            npx hardhat flatten "$file" > flattened/"$filename"
            echo "Analyzing $filename..."
            myth analyze flattened/"$filename" --solv 0.8.28 --execution-timeout 60
          done
